### ISSUE TITLE
Unable to build wheel for fdtdz

### ISSUE THREAD

**Issue by abulnaga1** [spinsphotonics/fdtdz#7]
Hello, I'm excited to try this package!
However, I am running into the following error when trying to install:
![image](https://user-images.githubusercontent.com/49005199/235720096-d453d104-19a0-413e-84c5-6ebdfa667083.png)

**Comment by jlu-spins** [comment]
Thanks for giving this a shot! Unfortunately, I'm going to need a lot more information about what's going on to help you out... Can you tell me as much information about your system and as much information on the install error (preferably copied in as plain text rather than a screenshot) as possible? Thank you
